name: SkyNeT CI  # 工作流名称

on:
  push:
    branches: [ "main", "master" ] # 当代码推送到这些分支时触发
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境

    steps:
    - name: 检出代码
      uses: [actions/checkout](https://github.com)@v4

    - name: 设置 Go 环境
      uses: [actions/setup-go](https://github.com)@v5
      with:
        go-version: '1.21' # 这里指定你需要的 1.21 版本

    - name: 安装依赖
      run: go mod tidy

    - name: 编译测试
      run: go build -v ./...

    - name: 运行测试
      run: go test -v ./...
